apiVersion: batch/v1
kind: Job
metadata:
  name: presync-delay
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: delay
          image: busybox
          command: ["sleep", "30"]